In [2]:
#ARRAYS
import numpy as np


In [3]:
#NUMPY(Numerical Python)

In [4]:
x=[0,1,2,3,4]
for i in x:
   print(i/2)

0.0
0.5
1.0
1.5
2.0


In [5]:
x=np.array([2,4,6,8,10])
print(x)

[ 2  4  6  8 10]


In [6]:
x/2

array([1., 2., 3., 4., 5.])

In [7]:
type(x)

numpy.ndarray

In [8]:
#numpy has a rich set of numpy function

#set 1 : random functions : used to develope random arrays

In [9]:
import numpy as np
np.random.randint(0,10,6)

array([9, 8, 7, 1, 7, 9], dtype=int32)

In [10]:
array = np.random.randint(0,10,(3,3))
print (array)

[[5 6 2]
 [7 5 2]
 [5 1 2]]


In [11]:
array = np.random.randint(0,10,(2,5))
array

array([[8, 6, 8, 7, 7],
       [9, 1, 5, 5, 5]], dtype=int32)

In [12]:
np.random.rand(10)

array([0.60648655, 0.17873945, 0.95607528, 0.23866856, 0.31205954,
       0.27023149, 0.8452889 , 0.07392434, 0.67516562, 0.46552487])

In [13]:
np.random.rand(2)

array([0.76273392, 0.2041981 ])

In [14]:
#NUMPY SLICING

In [15]:
data = np.random.randint(0,10,(5,4))
data

array([[3, 1, 1, 6],
       [0, 5, 2, 0],
       [3, 2, 7, 6],
       [9, 1, 8, 9],
       [6, 7, 3, 4]], dtype=int32)

In [16]:
data[1:,:2]

array([[0, 5],
       [3, 2],
       [9, 1],
       [6, 7]], dtype=int32)

In [17]:
data[2:4,1:]

array([[2, 7, 6],
       [1, 8, 9]], dtype=int32)

In [18]:
data.sum() # it will show the sum of all numbers present in the data array

np.int64(83)

In [19]:
data.max()        # it will show the max number that is present in the data array

np.int32(9)

In [20]:
data.min()        # it will show the min number that is present in the data array

np.int32(0)

In [21]:
# 1D Array

In [22]:
a = np.array([4,8,11])
print(a)

[ 4  8 11]


In [23]:
# 2D Array

In [24]:
b = np.array([[4,8,11],[16,45,1]])
print(b)

[[ 4  8 11]
 [16 45  1]]


In [25]:
# 3D Array

In [26]:
m1 = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[8,8,7]]])
print(m1)
type(m1)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [8 8 7]]]


numpy.ndarray

In [27]:
#Initialize numpy arrays

In [28]:
# initialize x X y dimentions with ' 0 ' values

In [29]:
# if we want all ' 0 's then zeros() will be used

In [30]:
np.zeros((4,2))   #initializing numpy array which have all the values ' 0 ' .

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
# if we want all ' 1 's then ones() will be used

In [32]:
np.ones((4,2))   #initializing numpy array which have all the values ' 1 ' .

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
# in case we want some other values except 0 & 1 then full() will be used

In [34]:
np.full((5,3),-3)

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [35]:
# initialize 'x' and 'y' with an interval of 'z'

In [36]:
# if we want numbers from x to y in the interval of 5 we use arange()

In [37]:
np.arange(0,101,5)    #it will show the numbers from 0 to 101 in the interval of 5 

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [38]:
np.arange(0,20)       #it will show the numbers from 0 to 20, by default it will take interval of 1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
# initialize z numbers between x and y

# divide upper and lower limit to equal measures

In [40]:
np.linspace(5,10,4)

array([ 5.        ,  6.66666667,  8.33333333, 10.        ])

In [41]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [42]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [43]:
# identical matrix

In [44]:
np.eye(5)     # here i will get the identical matrix i.e having 5 rows and 5 columns

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
np.eye(6) 

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [46]:
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
#ndarray.shape                     #it will shows howmany rows and howmany columns are there

In [48]:
print(m1.shape)                    #.shape will shows howmany rows and howmany columns are there

(2, 2, 3)


In [49]:
# we can use ndarray.shape to resize the array

In [50]:
a = np.array([[2,4,6,5],[1,9,11,6],[6,7,10,1]])
print("original array : \n", a)
a.shape = (6,2)
print("resized array : \n", a)

original array : 
 [[ 2  4  6  5]
 [ 1  9 11  6]
 [ 6  7 10  1]]
resized array : 
 [[ 2  4]
 [ 6  5]
 [ 1  9]
 [11  6]
 [ 6  7]
 [10  1]]


In [51]:
z = np.arange(24)
print(z)
# if i want to make a 3D array from the given array then 
z.shape = (6,2,2) #6 * 2 * 2 = 24, or we can use 4,3,2
print(z)
print(z.ndim)      #ndim refers how many dimentions are in the array, here 3D

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]
3


In [52]:
z = np.arange(30)
z.shape = (2,5,3)
print(z)
print(z.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
3


In [53]:
z = np.arange(30)
z.shape = (3,10)
print(z)
print(z.ndim)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
2


In [54]:
d = np.arange(24,dtype='float')   # if we won't mention dtype then it will take dtype = int
print(d)                                  # if we want float dtype then we have to mention dtype = float 


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]


In [55]:
a = np.array([[1,2,3],[4,5,6],[5,8,12]])
print(f"size : {a.size}")
print(f"shape : {a.shape}")
print(f"no.of dimentions : {a.ndim}")
print(f"datatype : {a.dtype}")

size : 9
shape : (3, 3)
no.of dimentions : 2
datatype : int64


In [56]:
x = np.random.randint(0,20,(6,5))
print(x)
print(x.shape)

[[ 3 11  1  8 19]
 [15  4  0 19  8]
 [17 17 11  2 19]
 [11  9 15  3  8]
 [ 3 11 18  6  4]
 [ 0 19 17 10 15]]
(6, 5)


In [57]:
x.shape   #shape tool gives a tuple of array dimention 
          #and can be used to change the dimention of an array

(6, 5)

In [58]:
x.reshape(10,3)     #reshape tool gives a new shape to an array
                    #without changing its data

array([[ 3, 11,  1],
       [ 8, 19, 15],
       [ 4,  0, 19],
       [ 8, 17, 17],
       [11,  2, 19],
       [11,  9, 15],
       [ 3,  8,  3],
       [11, 18,  6],
       [ 4,  0, 19],
       [17, 10, 15]], dtype=int32)

In [59]:
x.ravel()

array([ 3, 11,  1,  8, 19, 15,  4,  0, 19,  8, 17, 17, 11,  2, 19, 11,  9,
       15,  3,  8,  3, 11, 18,  6,  4,  0, 19, 17, 10, 15], dtype=int32)

In [60]:
y = x.ravel()
y

array([ 3, 11,  1,  8, 19, 15,  4,  0, 19,  8, 17, 17, 11,  2, 19, 11,  9,
       15,  3,  8,  3, 11, 18,  6,  4,  0, 19, 17, 10, 15], dtype=int32)

In [61]:
x1 = np.array([[2,3],[4,3]])
print(x1)

[[2 3]
 [4 3]]


In [62]:
x2 = np.array([[4,5],[6,7]])
print(x2)

[[4 5]
 [6 7]]


In [63]:
np.vstack([x1,x2])     #vertical stacking

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [64]:
np.hstack([x1,x2])     #horizontal stacking

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [65]:
np.concatenate([x1,x2],axis=0)     #vertical stacking

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [66]:
np.concatenate([x1,x2],axis=1)      #horizontal stacking

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [67]:
a = [10,20]
b = [20,5]
np.sum([a,b])

np.int64(55)

In [68]:
arr1 = np.array([[1,2,3],
                [4,5,6]])
arr2 = np.array([[7,8,9],
                 [10,11,12]])
#arr3 = np.array([[8,6,9],
                 #[10,9,13]])
sum_arrays = arr1 + arr2
print(f"addithon:\n{sum_arrays}")

addithon:
[[ 8 10 12]
 [14 16 18]]


In [69]:
arr1 = np.array([[1,2,3],
                [4,5,6]])
arr2 = np.array([[7,8,9],
                 [10,11,12]])
arr3 = np.array([[8,6,9],
                 [10,9,13]])
sum_arrays = arr1 + arr2 + arr3
print(f"addithon:\n{sum_arrays}")

addithon:
[[16 16 21]
 [24 25 31]]


In [70]:
np.subtract(10,8)

np.int64(2)

In [71]:
arr1 = np.array([[10,20,30],
                [40,50,60]])
arr2 = np.array([[7,8,9],
                 [10,11,12]])
#arr3 = np.array([[8,6,9],
                 #[10,9,13]])
subtract_arrays = arr1 - arr2
print(f"subtraction:\n{subtract_arrays}")

subtraction:
[[ 3 12 21]
 [30 39 48]]


In [72]:
arr1 = np.array([[10,20,30],
                [40,50,60]])
arr2 = np.array([[7,8,9],
                 [10,11,12]])
arr3 = np.array([[8,6,9],
                 [10,9,13]])
subtract_arrays = arr1 - arr2 - arr3
print(f"subtraction:\n{subtract_arrays}")

subtraction:
[[-5  6 12]
 [20 30 35]]


In [73]:
#broadcasting (using different shapes)
a = np.array([[1,2],[6,8]])
b = np.array([5,4])

# addition from each row of 'a' using broadcasing
result = a + b
print(f"result of a + b with broadcasting : \n {result}")


result of a + b with broadcasting : 
 [[ 6  6]
 [11 12]]


In [74]:
arr1 = np.array([[10,20,30],
                [40,50,60],])
arr2 = np.array([[7,8,9],
                 [10,11,12]])
#arr3 = np.array([[8,6,9],
                 #[10,9,13]])
multiplied_arrays = arr1 * arr2
print(f"multiplication:\n{multiplied_arrays}")

multiplication:
[[ 70 160 270]
 [400 550 720]]


In [75]:
arr1 = np.array([[10,20,30],
                [40,50,60],
                [10,11,12]])
arr2 = np.array([7,8,9])
#arr3 = np.array([[8,6,9],
                 #[10,9,13]])
multiplied_arrays = arr1 * arr2 
print(f"multiplication:\n{multiplied_arrays}")

multiplication:
[[ 70 160 270]
 [280 400 540]
 [ 70  88 108]]


In [76]:
#matrix multiplication

In [77]:
x1 = np.random.randint(0,10,(2,2))
x2 = np.random.randint(0,10,(2,2))



In [78]:
x1

array([[7, 6],
       [9, 1]], dtype=int32)

In [79]:
x2

array([[2, 5],
       [0, 2]], dtype=int32)

In [80]:
np.dot(x1,x2)

array([[14, 47],
       [18, 47]], dtype=int32)

In [81]:
x1 = np.random.randint(0,10,(3,2))
x2 = np.random.randint(0,10,(2,3))

In [82]:
x1

array([[7, 1],
       [6, 2],
       [8, 8]], dtype=int32)

In [83]:
x2

array([[3, 9, 6],
       [4, 4, 9]], dtype=int32)

In [84]:
np.dot(x1,x2)

array([[ 25,  67,  51],
       [ 26,  62,  54],
       [ 56, 104, 120]], dtype=int32)

In [85]:
x1 = np.random.randint(0,10,(3,2))
x2 = np.random.randint(0,10,(2,2))

In [86]:
x1

array([[1, 2],
       [3, 2],
       [0, 6]], dtype=int32)

In [87]:
x2

array([[5, 4],
       [4, 3]], dtype=int32)

In [88]:
np.dot(x1,x2)

array([[13, 10],
       [23, 18],
       [24, 18]], dtype=int32)

In [89]:
#string functions in arrays

In [90]:
x = np.array(['1','2','3','data'])

In [91]:
x

array(['1', '2', '3', 'data'], dtype='<U4')

In [92]:
np.char.capitalize(x)

array(['1', '2', '3', 'Data'], dtype='<U4')

In [93]:
np.char.center(x,10,fillchar='*')

array(['****1*****', '****2*****', '****3*****', '***data***'],
      dtype='<U10')

In [94]:
x = np.array([1,2,3,'data engineering'])

In [95]:
x

array(['1', '2', '3', 'data engineering'], dtype='<U21')

In [96]:
np.char.upper(x)

array(['1', '2', '3', 'DATA ENGINEERING'], dtype='<U21')

In [97]:
np.char.lower(x)

array(['1', '2', '3', 'data engineering'], dtype='<U21')

In [98]:
np.char.title(x)

array(['1', '2', '3', 'Data Engineering'], dtype='<U21')

In [99]:
y = np.array(["data science" , "machine learning"])

In [100]:
np.char.split(y,sep='e')

array([list(['data sci', 'nc', '']), list(['machin', ' l', 'arning'])],
      dtype=object)

In [101]:
np.char.count(y,"a")

array([2, 2])

In [102]:
np.char.startswith(y,"d")

array([ True, False])

In [103]:
np.char.replace(y,'a','**')

array(['d**t** science', 'm**chine le**rning'], dtype='<U18')

In [104]:
np.char.rjust(y,20,fillchar="*")

array(['********data science', '****machine learning'], dtype='<U20')

In [105]:
np.char.ljust(y,20,fillchar="?")

array(['data science????????', 'machine learning????'], dtype='<U20')

In [106]:
#time base functions

In [107]:
#division of array

In [108]:
arr1 = np.array([[10,20,30],
                [40,50,60],
                [10,11,12]])
arr2 = np.array([7,8,9])
#arr3 = np.array([[8,6,9],
                 #[10,9,13]])
divided_arrays = arr1 / arr2 
print(f"division:\n{divided_arrays}")

division:
[[1.42857143 2.5        3.33333333]
 [5.71428571 6.25       6.66666667]
 [1.42857143 1.375      1.33333333]]


In [109]:
#calculating exponential

In [110]:
a = np.array([1,2,3,4,5])
exp_a = np.exp(a)
print(f"original array : {a}")
print(f"exponential of the array : {exp_a}")

original array : [1 2 3 4 5]
exponential of the array : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [111]:
#square root

In [112]:
a = np.array([1,2,3,4,5])
print(f"square root of the array : {np.sqrt(a)}")
print(f"square root of the array : {np.exp(a)}")
print(f"square root of the array : {np.sqrt(a)}")


square root of the array : [1.         1.41421356 1.73205081 2.         2.23606798]
square root of the array : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
square root of the array : [1.         1.41421356 1.73205081 2.         2.23606798]


In [113]:
#aggregate function

In [114]:
a = np.array([1,2,3,4,5,6,7,8,9])
print("sum :",np.sum(a))
print("min :",np.min(a))
print("max :",np.max(a))
print("mean :",np.mean(a))
print("median :",np.median(a))

sum : 45
min : 1
max : 9
mean : 5.0
median : 5.0


In [115]:
#correlation & coefficient
data = np.random.randint(1,10,(5,5))
print(data)

[[4 9 5 5 1]
 [1 8 1 2 4]
 [5 2 3 2 9]
 [2 8 3 4 7]
 [3 3 1 9 6]]


In [ ]:
# data 
# 0 to 1 => +ve correlation
# -1 to 0 => -ve correlation
# 0 => no relation

In [116]:
np.corrcoef(data)

array([[ 1.        ,  0.53869736, -0.85244417,  0.22935309, -0.29561462],
       [ 0.53869736,  1.        , -0.09195402,  0.92340472, -0.01082997],
       [-0.85244417, -0.09195402,  1.        ,  0.17027321,  0.09746975],
       [ 0.22935309,  0.92340472,  0.17027321,  1.        ,  0.1666032 ],
       [-0.29561462, -0.01082997,  0.09746975,  0.1666032 ,  1.        ]])

In [117]:
np.corrcoef(data).astype(int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [118]:
np.round(np.corrcoef(data),2)

array([[ 1.  ,  0.54, -0.85,  0.23, -0.3 ],
       [ 0.54,  1.  , -0.09,  0.92, -0.01],
       [-0.85, -0.09,  1.  ,  0.17,  0.1 ],
       [ 0.23,  0.92,  0.17,  1.  ,  0.17],
       [-0.3 , -0.01,  0.1 ,  0.17,  1.  ]])